version: '3.8'

services:
  cart:
    build:
      context: ./cart_service
    platform: linux/arm64/v8
    mem_limit: 2000m
    mem_reservation: 2000M
    command: node index.js
    ports:
      - "3000:3000"

  discount:
    build:
      context: ./discount_service
    platform: linux/arm64/v8
    mem_limit: 2000m
    mem_reservation: 2000M
    command: node index.js
    depends_on:
      - cart
    ports:
      - "3001:3001"
