version: '3.8'

services:
  cart:
    build:
      context: ./cart-ms
    platform: linux/arm64/v8
    mem_limit: 1000m
    mem_reservation: 1000M
    command: node index.js
    volumes: 
      - ./cart-ms:/app

  discount:
    build:
      context: ./discount-ms
    platform: linux/arm64/v8
    mem_limit: 2000m
    mem_reservation: 2000M
    command: node index.js
    depends_on:
      - cart
    volumes: 
      - ./discount-ms:/app
