version: '3'
services:
  cart-ms:
    build:
      context: ./cart-ms
    platform: linux/arm64/v8
    command: node /app/main.js
    mem_limit: 1000m
    mem_reservation: 1000M
    volumes: 
      - ./cart-ms:/app

  discount-ms:
    build:
      context: ./discount-ms
    depends_on:
      - cart-ms
    platform: linux/arm64/v8
    command: node /app/main.js
    mem_limit: 2000m
    mem_reservation: 2000M
    volumes: 
      - ./discount-ms:/app
